"""Compatibility shim for the refactored session runtime in session_new.

All runtime logic now lives in eve.agent.session.session_new. This module re-exports
public APIs so existing imports continue to function while the rest of the codebase
migrates to the new package."""

from eve.agent.session.models import (
    Channel,
    ChatMessage,
    ChatMessageObservability,
    LLMConfig,
    LLMContextMetadata,
    LLMTraceMetadata,
    PromptSessionContext,
    Session,
    SessionMessage,
    SessionBudget,
    SessionMemoryContext,
    SessionUpdate,
    ToolCall,
    UpdateType,
)
from eve.agent.session.session_llm import LLMContext

from .session_new import (
    SessionCancelledException,
    add_chat_message,
    async_prompt_session,
    async_run_tool_call_with_cancellation,
    async_title_session,
    build_llm_context,
    build_prompt_session_context,
    build_system_extras,
    build_system_message,
    check_if_session_active,
    check_session_budget,
    convert_message_roles,
    create_eden_message,
    create_fake_tool_result,
    create_session_message_notification,
    determine_actors,
    format_session_update,
    generate_session_title,
    label_message_channels,
    parse_mentions,
    process_tool_call,
    process_tool_calls,
    prepare_prompt_session,
    run_prompt_session,
    run_prompt_session_stream,
    setup_session,
    update_session_budget,
    validate_prompt_session,
)

__all__ = [
    "Channel",
    "ChatMessage",
    "ChatMessageObservability",
    "LLMConfig",
    "LLMContext",
    "LLMContextMetadata",
    "LLMTraceMetadata",
    "PromptSessionContext",
    "Session",
    "SessionBudget",
    "SessionCancelledException",
    "SessionMemoryContext",
    "SessionMessage",
    "SessionUpdate",
    "ToolCall",
    "UpdateType",
    "add_chat_message",
    "async_prompt_session",
    "async_run_tool_call_with_cancellation",
    "async_title_session",
    "build_llm_context",
    "build_prompt_session_context",
    "build_system_extras",
    "build_system_message",
    "check_if_session_active",
    "check_session_budget",
    "convert_message_roles",
    "create_eden_message",
    "create_fake_tool_result",
    "create_session_message_notification",
    "determine_actors",
    "format_session_update",
    "generate_session_title",
    "label_message_channels",
    "parse_mentions",
    "process_tool_call",
    "process_tool_calls",
    "prepare_prompt_session",
    "run_prompt_session",
    "run_prompt_session_stream",
    "setup_session",
    "update_session_budget",
    "validate_prompt_session",
]
