name: Deploy Discord Gateway

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'eve/clients/discord/gateway.py'

jobs:
  deploy-gateway:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout workflows repo
        uses: actions/checkout@v4
        with:
          repository: edenartlab/workflows
          path: workflows

      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: eve

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4

      - name: Install dependencies
        working-directory: eve
        run: rye sync

      - name: Configure Modal token
        working-directory: eve
        run: rye run modal token set --token-id ${{ secrets.MODAL_TOKEN_ID }} --token-secret ${{ secrets.MODAL_TOKEN_SECRET }}

      - name: Set DB environment based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DB=PROD" >> $GITHUB_ENV
          else
            echo "DB=STAGE" >> $GITHUB_ENV
          fi

      - name: Deploy Discord Gateway to Modal
        working-directory: eve
        run: rye run modal deploy ./eve/clients/discord/gateway.py